### PR TITLE
Added download button

### LINKED ISSUE #6: Allow downloading of City models
Allow the downloading of City 3D models, similar to how [Github Skylines](https://skyline.github.com/) does.

I am not sure how complicated this would be though I haven't really dealt with javascript 3D models in the past, so I am not sure what this would require.

### PR DESCRIPTION
**Pull request by eggplants**
Closes: #6 

---

On clicking download button, `<name>-<year>-city.stl` will be downloaded.

(size: 253.9 MB)

---

@honzaap Please add `fa-arrow-down-from-line` to your AwesomeFont Kit.

### CODE REVIEW

**Comment by honzaap** [comment]
Looks fine. Since I'm broke I use the free tier of font awesome so please replace ```fa-arrow-down-from-line``` with ```fa-solid fa-download``` or some other working free icon if you like. I'll merge it then and make a build for GH pages :)

**Comment by eggplants** [comment]
image

**Comment by honzaap** [comment]
Looks fine, thank you 👍

**Comment by eggplants** [comment]
To improve compatibility and performance of saving files, maybe we should use [eligrey/FileSaver.js](https://github.com/eligrey/FileSaver.js)

**Pull request merged**
